name: "Check code quality"

on:
  push:
    branches: [ "main" ]  # Only run on main branch, not master (our deployment branch)
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install all dependencies
      run: pip install .[dev]
    - name: Run mypy
      run: mypy --pretty src examples
    - name: Run pylint
      run: pylint examples src
    - name: Run isort
      run: isort --check-only --diff .
    - name: Run black
      run: black --check --diff .
